package com.example.edumap.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.springframework.stereotype.Service;

@Service
public class ExportService {

    public byte[] generateCourseProposal(String courseCode, String courseTitle, 
                                         String courseBranch, String courseSem,
                                         List<String> cos, List<Map<String, Object>> syllabus,
                                         String mode) throws IOException {
        
        XWPFDocument document = new XWPFDocument();
        
        // Title
        XWPFParagraph titlePara = document.createParagraph();
        titlePara.setAlignment(ParagraphAlignment.CENTER);
        XWPFRun titleRun = titlePara.createRun();
        titleRun.setText("COURSE PROPOSAL");
        titleRun.setBold(true);
        titleRun.setFontSize(16);
        
        // Subtitle
        XWPFParagraph subtitlePara = document.createParagraph();
        subtitlePara.setAlignment(ParagraphAlignment.CENTER);
        XWPFRun subtitleRun = subtitlePara.createRun();
        subtitleRun.setText("Generated by CAMP (Course Alignment & Mapping Portal)");
        subtitleRun.setItalic(true);
        subtitleRun.setFontSize(11);
        subtitleRun.setColor("666666");
        
        // Basic Info Section
        XWPFParagraph spacer1 = document.createParagraph();
        spacer1.setSpacingAfter(120);
        
        XWPFParagraph infoHeaderPara = document.createParagraph();
        XWPFRun infoHeaderRun = infoHeaderPara.createRun();
        infoHeaderRun.setText("COURSE INFORMATION");
        infoHeaderRun.setBold(true);
        infoHeaderRun.setFontSize(12);
        
        // Course Info Table
        XWPFTable infoTable = document.createTable(4, 2);
        infoTable.setWidth(5000);
        
        addTableCell(infoTable, 0, 0, "Course Code:");
        addTableCell(infoTable, 0, 1, courseCode);
        addTableCell(infoTable, 1, 0, "Course Title:");
        addTableCell(infoTable, 1, 1, courseTitle);
        addTableCell(infoTable, 2, 0, "Branch:");
        addTableCell(infoTable, 2, 1, courseBranch);
        addTableCell(infoTable, 3, 0, "Semester:");
        addTableCell(infoTable, 3, 1, courseSem);
        
        // COs Section
        XWPFParagraph spacer2 = document.createParagraph();
        spacer2.setSpacingBefore(240);
        spacer2.setSpacingAfter(120);
        
        XWPFParagraph coHeaderPara = document.createParagraph();
        XWPFRun coHeaderRun = coHeaderPara.createRun();
        coHeaderRun.setText("COURSE OUTCOMES");
        coHeaderRun.setBold(true);
        coHeaderRun.setFontSize(12);
        
        for (int i = 0; i < cos.size(); i++) {
            XWPFParagraph coPara = document.createParagraph();
            XWPFRun coRun = coPara.createRun();
            coRun.setText("CO" + (i + 1) + ": " + cos.get(i));
        }
        
        // Syllabus Section
        XWPFParagraph spacer3 = document.createParagraph();
        spacer3.setSpacingBefore(240);
        spacer3.setSpacingAfter(120);
        
        XWPFParagraph syllabusPara = document.createParagraph();
        XWPFRun syllabusRun = syllabusPara.createRun();
        syllabusRun.setText(mode.equals("B") ? "GENERATED SYLLABUS" : "UPDATED SYLLABUS");
        syllabusRun.setBold(true);
        syllabusRun.setFontSize(12);
        
        if (syllabus != null) {
            for (Map<String, Object> unit : syllabus) {
                XWPFParagraph unitPara = document.createParagraph();
                unitPara.setSpacingBefore(120);
                XWPFRun unitRun = unitPara.createRun();
                unitRun.setText("Unit " + unit.get("num") + ": " + unit.get("title"));
                unitRun.setBold(true);
                
                XWPFParagraph topicPara = document.createParagraph();
                XWPFRun topicRun = topicPara.createRun();
                topicRun.setText(unit.get("topics").toString());
                topicRun.setFontSize(10);
            }
        }
        
        // Footer
        XWPFParagraph spacer4 = document.createParagraph();
        spacer4.setSpacingBefore(240);
        
        XWPFParagraph footerPara = document.createParagraph();
        footerPara.setAlignment(ParagraphAlignment.CENTER);
        XWPFRun footerRun = footerPara.createRun();
        footerRun.setText("--- End of Course Proposal ---");
        footerRun.setItalic(true);
        footerRun.setColor("999999");
        footerRun.setFontSize(9);
        
        // Convert to bytes
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        document.write(out);
        document.close();
        
        return out.toByteArray();
    }
    
    private void addTableCell(XWPFTable table, int row, int col, String text) {
        XWPFTableCell cell = table.getRow(row).getCell(col);
        XWPFParagraph para = cell.getParagraphs().get(0);
        XWPFRun run = para.createRun();
        run.setText(text);
        if (col == 0) {
            run.setBold(true);
        }
    }
}
